/** Mirrors backend `constants/permissions.ts` for UI gating. */
export const P = {
  PLATFORM_READ: "PLATFORM.READ",
  PLATFORM_CREATE: "PLATFORM.CREATE",
  PLATFORM_UPDATE: "PLATFORM.UPDATE",
  TASKS_ASSIGN: "TASKS.ASSIGN",
  TASKS_REVIEW: "TASKS.REVIEW",
  TASKS_READ: "TASKS.READ",
  TASKS_CREATE: "TASKS.CREATE",
  TASKS_UPDATE: "TASKS.UPDATE",
  TASKS_DELETE: "TASKS.DELETE",

  USERS_READ: "USERS.READ",
  USERS_CREATE: "USERS.CREATE",
  USERS_UPDATE: "USERS.UPDATE",
  USERS_DELETE: "USERS.DELETE",

  ROLES_READ: "ROLES.READ",
  ROLES_CREATE: "ROLES.CREATE",
  ROLES_UPDATE: "ROLES.UPDATE",
  ROLES_DELETE: "ROLES.DELETE",

  DEPARTMENTS_READ: "DEPARTMENTS.READ",
  DEPARTMENTS_CREATE: "DEPARTMENTS.CREATE",
  DEPARTMENTS_UPDATE: "DEPARTMENTS.UPDATE",
  DEPARTMENTS_DELETE: "DEPARTMENTS.DELETE",

  REPORTS_READ: "REPORTS.READ",
  REPORTS_CREATE: "REPORTS.CREATE",
  REPORTS_UPDATE: "REPORTS.UPDATE",
  REPORTS_DELETE: "REPORTS.DELETE",

  SETTINGS_READ: "SETTINGS.READ",
  SETTINGS_CREATE: "SETTINGS.CREATE",
  SETTINGS_UPDATE: "SETTINGS.UPDATE",
  SETTINGS_DELETE: "SETTINGS.DELETE",

  MEETINGS_READ: "MEETINGS.READ",
  MEETINGS_CREATE: "MEETINGS.CREATE",
  MEETINGS_UPDATE: "MEETINGS.UPDATE",
  MEETINGS_DELETE: "MEETINGS.DELETE",
} as const;

export const PERMISSION_MATRIX_MODULES = [
  "TASKS",
  "USERS",
  "ROLES",
  "DEPARTMENTS",
  "REPORTS",
  "SETTINGS",
  "MEETINGS",
] as const;

export const PERMISSION_MATRIX_ACTIONS = [
  "READ",
  "CREATE",
  "UPDATE",
  "DELETE",
] as const;
